version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region eu-west-1 --no-include-email --debug) 
      - REPOSITORY_URI=845280847960.dkr.ecr.eu-west-1.amazonaws.com/dev-ecr-phe-covid-19
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - ls -al
      - docker build -t 845280847960.dkr.ecr.eu-west-1.amazonaws.com/dev-ecr-phe-covid-19:latest .
      - docker tag 845280847960.dkr.ecr.eu-west-1.amazonaws.com/dev-ecr-phe-covid-19:latest 845280847960.dkr.ecr.eu-west-1.amazonaws.com/dev-ecr-phe-covid-19:$IMAGE_TAG
  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 845280847960.dkr.ecr.eu-west-1.amazonaws.com/dev-ecr-phe-covid-19:latest
      - docker push 845280847960.dkr.ecr.eu-west-1.amazonaws.com/dev-ecr-phe-covid-19:$IMAGE_TAG