version: "3"

services:
  web:
    environment:
      DBNAME: "${DBNAME}"
      DBHOST: "${DBHOST}"
      DBUSER: "${DBUSER}"
      DBPORT: "${DBPORT}"
      DBPASSWORD: "${DBPASSWORD}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_BUCKET_NAME: "${AWS_BUCKET_NAME}"
      AWS_REGION: "${AWS_REGION}"
      AWS_STORAGE_BUCKET_NAME: "${AWS_STORAGE_BUCKET_NAME}"
      AWS_ACCESS_KEY_ID_DEPLOYMENT: "${AWS_ACCESS_KEY_ID_DEPLOYMENT}"
      AWS_SECRET_ACCESS_KEY_DEPLOYMENT: "${AWS_SECRET_ACCESS_KEY_DEPLOYMENT}"
      AWS_STORAGE_BUCKET_NAME_DEPLOYMENT: "${AWS_STORAGE_BUCKET_NAME_DEPLOYMENT}"
      AWS_REGION_DEPLOYMENT: "${AWS_REGION_DEPLOYMENT}"
      ROOT_DOMAIN: "${ROOT_DOMAIN}"
      AZURE_FILE_ACCOUNT_NAME: "${AZURE_FILE_ACCOUNT_NAME}"
      AZURE_FILE_ACCOUNT_KEY: "${AZURE_FILE_ACCOUNT_KEY}"
      AZURE_FILE_SHARE: "${AZURE_FILE_SHARE}"
      LOCAL: "${LOCAL}"
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
