# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial')
    ]

    operations = [
        migrations.RunSQL("INSERT INTO auth_user (password, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) VALUES ('pbkdf2_sha256$150000$0HQzv9wWvWM3$+oSPaRB6T+IiG2VauwOi01W2TFjgjZElFxlYRrpvxUI=', '1', 'superuser', 'Default', 'User', '', '1', '1', (SELECT NOW()));"),
    ]
