# Generated by Django 2.2.11 on 2020-03-23 09:27

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_default_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_items',
            field=wagtail.core.fields.StreamField([('simple_menu_item', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(help_text='Leave blank to use the page name', required=False)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False))]))]),
        ),
    ]
