# Generated by Django 2.2.10 on 2020-03-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200322_2002'),
        ('core', '0003_auto_20200323_0927'),
    ]

    operations = [
    ]
