# Generated by Django 2.2.11 on 2020-03-31 14:46

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20200323_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='footer_items',
            field=wagtail.core.fields.StreamField([('footer_item', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(help_text='Leave blank to use the page name', required=False)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.core.blocks.CharBlock(required=False))]))]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_items',
            field=wagtail.core.fields.StreamField([('simple_menu_item', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(help_text='Leave blank to use the page name', required=False)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.core.blocks.CharBlock(required=False))]))]),
        ),
    ]
