# Generated by Django 2.2.12 on 2020-04-14 09:59

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200331_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='footer_items',
            field=wagtail.core.fields.StreamField([('footer_item', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(help_text='Leave blank to use the page name', required=False)), ('link_page', wagtail.core.blocks.PageChooserBlock(help_text='Link to an internal page', required=False)), ('link_url', wagtail.core.blocks.CharBlock(help_text='Link to an external page', required=False))]))]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_items',
            field=wagtail.core.fields.StreamField([('simple_menu_item', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(help_text='Leave blank to use the page name', required=False)), ('link_page', wagtail.core.blocks.PageChooserBlock(help_text='Link to an internal page', required=False)), ('link_url', wagtail.core.blocks.CharBlock(help_text='Link to an external page', required=False))]))]),
        ),
    ]
