# Generated by Django 2.2.11 on 2020-04-16 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200408_0957'),
        ('core', '0006_auto_20200416_1028'),
    ]

    operations = [
    ]
