# Generated by Django 2.2.11 on 2020-04-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200414_0959'),
        ('core', '0007_merge_20200416_1038'),
    ]

    operations = [
    ]
