# Generated by Django 2.2.12 on 2020-04-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20200416_1038'),
        ('core', '0006_auto_20200414_0959'),
    ]

    operations = [
    ]
