# Generated by Django 2.2.12 on 2020-05-04 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20200424_1243'),
        ('core', '0008_merge_20200423_1307'),
    ]

    operations = [
    ]
