# Generated by Django 2.2.12 on 2020-05-19 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('core', '0009_merge_20200504_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodsRedirect',
            fields=[
                ('redirect_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailredirects.Redirect')),
            ],
            bases=('wagtailredirects.redirect',),
        ),
    ]
