# Generated by Django 2.2.12 on 2020-05-20 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_methodsredirect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methodsredirect',
            options={'verbose_name': 'Redirect'},
        ),
    ]
