# Generated by Django 2.2.10 on 2020-03-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpage',
            name='sub_heading',
            field=models.TextField(blank=True),
        ),
    ]
