# Generated by Django 2.2.11 on 2020-03-26 14:58

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscriptionpage_sub_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpage',
            name='subscription_service_pending_message',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
