# Generated by Django 2.2.11 on 2020-03-21 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('contentPages', '0003_resourceitempage'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceitempage',
            name='link_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
