# Generated by Django 2.2.11 on 2020-03-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0005_auto_20200322_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcespage',
            name='usage_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
