# Generated by Django 2.2.11 on 2020-03-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0006_resourcespage_usage_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResourceItemPreview',
        ),
    ]
