# Generated by Django 2.2.10 on 2020-03-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0010_homepage_homepagecampaign'),
        ('contentPages', '0010_auto_20200323_1458'),
    ]

    operations = [
    ]
