# Generated by Django 2.2.11 on 2020-03-25 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('contentPages', '0011_merge_20200324_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcespage',
            old_name='usage_notes',
            new_name='sidebar_note',
        ),
        migrations.AddField(
            model_name='resourcespage',
            name='sidebar_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
