# Generated by Django 2.2.11 on 2020-03-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0012_auto_20200325_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcespage',
            name='sidebar_screenreader_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
