# Generated by Django 2.2.11 on 2020-04-16 10:28

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0014_resourceitempage_upload_link'),
    ]

    operations = [

    ]
