# Generated by Django 2.2.12 on 2020-04-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0014_resourceitempage_upload_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='overview_subpage_heading',
            field=models.TextField(default='Overview'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='resources_subpage_heading',
            field=models.TextField(default='Resources'),
        ),
    ]
