# Generated by Django 2.2.12 on 2020-05-06 10:39

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0015_auto_20200414_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='signup_intro',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
