# Generated by Django 2.2.11 on 2020-04-09 13:49

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('contentPages', '0015_auto_20200408_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReusableContent',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('name', models.CharField(max_length=100)),
                ('content_body', wagtail.core.fields.RichTextField(default='')),
            ],
            options={
                'verbose_name': 'Content Title',
                'verbose_name_plural': 'Content Titles',
            },
            bases=('wagtailcore.page',),
        ),
    ]
