# Generated by Django 2.2.11 on 2020-04-09 14:24

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contentPages', '0016_reusablecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('content_body', wagtail.core.fields.RichTextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Shared Content',
            },
        ),
        migrations.DeleteModel(
            name='ReusableContent',
        ),
    ]
