# Generated by Django 2.2.12 on 2020-04-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0022_auto_20200416_1158'),
        ('contentPages', '0015_auto_20200414_0959'),
    ]

    operations = [
    ]
