# Generated by Django 2.2.11 on 2020-04-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0015_auto_20200414_0959'),
        ('contentPages', '0022_auto_20200416_1158'),
    ]

    operations = [
    ]
