# Generated by Django 2.2.12 on 2020-04-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0016_allresources_assettype'),
        ('contentPages', '0023_merge_20200423_1307'),
    ]

    operations = [
    ]
