# Generated by Django 2.2.11 on 2020-04-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0024_auto_20200424_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceitempage',
            name='tags',
        ),
        migrations.AddField(
            model_name='resourceitempage',
            name='asset_type',
            field=models.CharField(choices=[('posters', 'Poster'), ('digital_screens', 'Digital Screens'), ('social_media', 'Social Media Resources'), ('web_banners', 'Web Banners'), ('alternative_resources', 'Alternative Resources')], default='posters', max_length=25),
        ),
        migrations.DeleteModel(
            name='DocumentTags',
        ),
    ]
