# Generated by Django 2.2.11 on 2020-04-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0025_auto_20200424_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourceitempage',
            old_name='asset_type',
            new_name='document_type',
        ),
    ]
