# Generated by Django 2.2.11 on 2020-04-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0026_auto_20200424_1627'),
        ('contentPages', '0016_allresources_assettype'),
    ]

    operations = [
    ]
