# Generated by Django 2.2.11 on 2020-04-27 09:59

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
        ('contentPages', '0027_merge_20200427_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllResourcesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('heading', models.TextField(blank=True)),
                ('subtitle', models.TextField(blank=True)),
                ('signup_intro', models.TextField(blank=True)),
                ('asset_list_header', models.TextField(default='Resources List')),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameModel(
            old_name='AssetType',
            new_name='AllResourcesTile',
        ),
        migrations.AlterField(
            model_name='allresourcestile',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_types', to='contentPages.AllResourcesPage'),
        ),
        migrations.AlterField(
            model_name='resourceitempage',
            name='document_type',
            field=models.CharField(choices=[('posters', 'Poster'), ('digital_screens', 'Digital Screen'), ('social_media', 'Social Media Resource'), ('web_banners', 'Web Banner'), ('alternative_resources', 'Alternative Resource')], default='posters', max_length=25),
        ),
        migrations.DeleteModel(
            name='AllResources',
        ),
    ]
