# Generated by Django 2.2.11 on 2020-04-27 14:24

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('contentPages', '0028_auto_20200427_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allresourcestile',
            name='caption',
            field=models.CharField(choices=[('posters', 'Poster'), ('digital_screens', 'Digital Screen'), ('social_media', 'Social Media Resource'), ('web_banners', 'Web Banner'), ('alternative_resources', 'Alternative Resource')], default='posters', max_length=25),
        ),
        migrations.CreateModel(
            name='AssetTypePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('heading', models.TextField(blank=True)),
                ('subtitle', models.TextField(blank=True)),
                ('signup_intro', models.TextField(blank=True)),
                ('asset_type_header', models.TextField(default='Type Resources')),
                ('document_type', models.CharField(choices=[('posters', 'Poster'), ('digital_screens', 'Digital Screen'), ('social_media', 'Social Media Resource'), ('web_banners', 'Web Banner'), ('alternative_resources', 'Alternative Resource')], default='posters', max_length=25)),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
