# Generated by Django 2.2.11 on 2020-04-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0023_merge_20200423_1307'),
        ('contentPages', '0029_auto_20200427_1424'),
    ]

    operations = [
    ]
