# Generated by Django 2.2.11 on 2020-05-01 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0030_merge_20200429_0954'),
        ('contentPages', '0024_merge_20200430_1219'),
    ]

    operations = [
    ]
