# Generated by Django 2.2.11 on 2020-04-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0031_merge_20200501_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceitempage',
            name='document_type',
            field=models.CharField(choices=[('posters', 'Poster'), ('digital_screens', 'Digital Screens'),
                                            ('social_media', 'Social Media Resources'), ('web_banners', 'Web Banners'),
                                            ('alternative_resources', 'Alternative Resources')], default='posters',
                                   max_length=25),
        ),
    ]
