# Generated by Django 2.2.12 on 2020-05-12 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0017_auto_20200507_1147'),
        ('contentPages', '0033_auto_20200505_1041'),
    ]

    operations = [
    ]
