# Generated by Django 2.2.11 on 2020-05-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0034_merge_20200512_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateNewResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_resource_type', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Resource Types',
            },
        ),
    ]
