# Generated by Django 2.2.11 on 2020-05-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0035_createnewresourcetype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createnewresourcetype',
            options={'verbose_name': 'Resource Type'},
        ),
        migrations.AddField(
            model_name='createnewresourcetype',
            name='available_resource_types',
            field=models.CharField(choices=[('posters', 'Poster'), ('digital_screens', 'Digital Screen'), ('alternative_formats', 'Alternative Format'), ('digital_out_of_home', 'Digital out-of-home'), ('email_signatures', 'Email Signature'), ('fact_sheets', 'Fact Sheet'), ('leaflet', 'Leaflet'), ('lockup', 'Lockup'), ('pm_letter', 'PM Letter'), ('press_release', 'Press Release')], default='', max_length=25),
        ),
    ]
