# Generated by Django 2.2.11 on 2020-05-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0036_auto_20200519_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createnewresourcetype',
            old_name='new_resource_type',
            new_name='resource_type',
        ),

        migrations.RemoveField(
            model_name='createnewresourcetype',
            name='available_resource_types',
        ),
    ]
