# Generated by Django 2.2.11 on 2020-05-19 16:16

from django.db import migrations
from CMS.enums import enums


def convert_existing_resource_types(apps, schema_editor):
    CreateNewResourceTypes = apps.get_model("contentPages", "CreateNewResourceTypes")
    for asset_type in enums.asset_types:
        new_resource_type = CreateNewResourceTypes(resource_type=asset_type[1])
        new_resource_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0036_auto_20200519_1615'),
    ]

    operations = [
        migrations.RunPython(convert_existing_resource_types),

        migrations.RenameField(
            model_name='createnewresourcetype',
            old_name='new_resource_type',
            new_name='resource_type',
        ),
    ]
