# Generated by Django 2.2.12 on 2020-05-20 19:41

from django.db import migrations, models
import django.db.models.deletion

def create_new_draft_revisions(apps, schema_editor):
    AllResourcesTile = apps.get_model("contentPages", "AllResourcesTile")
    AssetTypePage = apps.get_model("contentPages", "AssetTypePage")
    ResourceItemPage = apps.get_model("contentPages", "ResourceItemPage")

    resource_tiles = AllResourcesTile.objects.filter(live=False)
    for resource_tile in resource_tiles:
        resource_tile.save_revision()

    asset_type_pages = AssetTypePage.objects.filter(live=False)
    for asset_type_page in asset_type_pages:
        asset_type_page.save_revision()

    resource_items = ResourceItemPage.objects.filter(live=False)
    for resource_item in resource_items:
        resource_item.save_revision()


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0039_auto_20200520_1941'),
    ]

    operations = [
        migrations.RunPython(create_new_draft_revisions),
    ]
