# Generated by Django 2.2.12 on 2020-05-20 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0035_new_revision_for_draft_landing_pages'),
        ('contentPages', '0040_draft_resource_types'),
    ]

    operations = [
    ]
