# Generated by Django 2.2.12 on 2020-05-29 10:10

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0041_merge_20200520_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcespage',
            name='signup_message',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
