# Generated by Django 2.2.12 on 2020-07-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0042_auto_20200529_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecampaign',
            name='external_link',
            field=models.TextField(blank=True),
        ),
    ]
