# Generated by Django 2.2.14 on 2020-11-23 11:03

from django.db import migrations
import wagtail.core.fields

from contentPages.models import LandingPage


def migrate_away_from_shared_snippets(apps, schema_editor):
    landing_pages = LandingPage.objects.all()
    for landing_page in landing_pages:
        if landing_page.overview_subpage_body:
            landing_page.overview_subpage_text = landing_page.overview_subpage_body.content_body
        if landing_page.resources_subpage_body:
            landing_page.resources_subpage_text = landing_page.resources_subpage_body.content_body
        landing_page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0044_externalresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='overview_subpage_text',
            field=wagtail.core.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='resources_subpage_text',
            field=wagtail.core.fields.RichTextField(blank=True, default=''),
        ),
        migrations.RunPython(migrate_away_from_shared_snippets),
    ]
