# Generated by Django 2.2.20 on 2021-05-18 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contentPages', '0046_accessibilitystatement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessibilityStatement',
        ),
    ]
