# Generated by Django 2.2.20 on 2021-05-18 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('contentPages', '0049_flexpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlexPage',
        ),
    ]
