# Generated by Django 2.2.20 on 2021-05-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0050_delete_flexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessibilitystatement',
            name='heading',
            field=models.TextField(),
        ),
    ]
