# Generated by Django 2.2.20 on 2021-05-19 08:48

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contentPages', '0051_auto_20210518_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibilitystatement',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessibilitystatement',
            name='subtitle',
            field=models.TextField(default='Accessibility Statement'),
        ),
    ]
